package fr.rakambda.rsndiscord.spring.api.anilist.response.gql.notification;

public enum NotificationType{
	ACTIVITY_LIKE,
	ACTIVITY_MENTION,
	ACTIVITY_MESSAGE,
	ACTIVITY_REPLY,
	ACTIVITY_REPLY_LIKE,
	ACTIVITY_REPLY_SUBSCRIBED,
	AIRING,
	FOLLOWING,
	RELATED_MEDIA_ADDITION,
	THREAD_COMMENT_LIKE,
	THREAD_COMMENT_MENTION,
	THREAD_COMMENT_REPLY,
	THREAD_LIKE,
	THREAD_SUBSCRIBED,
	MEDIA_DATA_CHANGE,
	MEDIA_MERGE,
	MEDIA_DELETION
}
